version: '3.5'
services:
  db:
    platform: linux/x86_64
    image: 'mariadb'
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: p@55w0rd
      MYSQL_DATABASE: profile
    networks:
      - localhost

  profile:
    build: 
        context: .
        dockerfile: Dockerfile
        target: run
    container_name: profile
    entrypoint: /bin/bash -c ./entrypoint.sh
    volumes:
      - $PWD:/app
    depends_on:
      -  db
    env_file:
      - $PWD/.doppler
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 8080:80
    networks:
      - localhost

networks:
  localhost:
    driver: bridge
    external: false