apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ default 1 .Values.profileManager.deployment.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.profileManager.deployment.image.repository }}"
        imagePullPolicy: IfNotPresent
        env:
          - name: DOPPLER_PROJECT
            valueFrom:
              secretKeyRef:
                  key: DOPPLER_PROJECT
                  name: {{ .Values.profileManager.secrets.doppler.name }}
          - name: DOPPLER_TOKEN
            valueFrom:
              secretKeyRef:
                  key: DOPPLER_TOKEN
                  name: {{ .Values.profileManager.secrets.doppler.name }}
        ports:
        - containerPort: {{ .Values.profileManager.deployment.service.internalPort | int }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.profileManager.deployment.service.internalPort | int }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.profileManager.deployment.service.internalPort | int }}
        resources:
{{ toYaml .Values.resources | indent 10 }}