{{- range $secretKey,$secret := .Values.profileManager.secrets }}
apiVersion: v1
kind: Secret
metadata:
    name: "{{ $secret.name }}"
data:
{{- range $dataKey,$dataVal := $secret.data }}
{{- if $secret.encrypt}}
    {{ $dataKey }}: {{  $dataVal | b64enc }}
{{- else }}
    {{ $dataKey }}: {{  $dataVal }}
{{- end }}
{{- end }}
---
{{- end -}}
